### ISSUE TITLE
small damage done to your apache licenses?

### ISSUE THREAD

**Issue by pombredanne** [blokur/harego#22]
While running a license scan with my scancode-toolkit, I found out your Apache license text is subtly damaged, likely from a global search and replace. "communication" is replaced by "token" like in https://github.com/blokur/testament/blob/d53fcb97598ae8cfa50fe4629d1888f37c861bc1/LICENSE#L54 
This seems to affect many or most of Apache-licensed repos

**Comment by arsham** [comment]
Thank you for reporting this. I will fix the license as soon as I get a chance.
I'm wondering how did you find this licensing issue?
